---
spring:
  cloud:
    bus:
      enabled: false
  aop:
    proxy-target-class: true
    auto: true
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  thymeleaf:
    mode: HTML
    cache: false
    encoding: UTF-8
server:
  connection-timeout: 20000
  context-path: /
  tomcat:
    basedir: build/tomcat
    remote-ip-header: X-FORWARDED-FOR
    uri-encoding: UTF-8
    protocol-header: X-Forwarded-Proto
    protocol-header-https-value: https
    port-header: X-Forwarded-Port
    max-threads: 10
    max-http-post-size: 2097152
    accesslog:
      pattern: '%t %a \%r\ %s (%D ms)'
      suffix: .log
      enabled: true
  port: 9000
  max-http-header-size: 2097152
  session:
    tracking-modes: COOKIE
    cookie:
      http-only: true
    timeout: 300
  context-parameters:
    isLog4jAutoInitializationDisabled: true
  compression:
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain
    enabled: true
  error:
    include-stacktrace: ALWAYS
  ssl:
    keyAlias: tomcat
    key-store: classpath:tomcat.keystore
    key-store-password: yellowcong
    enabled: true
  use-forward-headers: true
security:
  basic:
    path: /status/**
    authorize-mode: role
    enabled: false
endpoints:
  restart:
    enabled: false
  sensitive: true
  shutdown:
    enabled: false
  enabled: false
cas:
  tgc:
    secure: false
  logout:
    followServiceRedirects: true
  serviceRegistry:
    initFromJson: true
  ticket:
    tgt:
      rememberMe:
        timeToKillInSeconds: 3600
        enabled: true
  warningCookie:
    secure: false
  authn:
    accept:
      users: yellowcong::yellowcong
management:
  security:
    sessions: if_required
    roles: ACTUATOR,ADMIN
    enabled: true
  context-path: /status
  add-application-context-header: false
